baseURL        = "https://example.com/"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
theme          = "hermit-v2"
enableRobotsTXT = true
title   = "2026 SPS Modeling Competition"

[params]
  homeSubtitlePrinter = true
  homeSubtitle     = "Presented by Georgia Tech Society of Physics Students."
  code_copy_button = true
  scrollToTop      = true
  shareSocial      = false

[[menus.main]]
  name   = "Register"
  url    = "/Register/"
  weight = 10

[[menus.main]]
  name   = "Volunteer"
  url    = "/Volunteer/"
  weight = 12

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[menus.main]]
  name   = "Information"
  url    = "/Information/"
  weight = 15

[[menus.main]]
  name   = "SPS Homepage"
  url    = "https://sps.physics.gatech.edu/"
  weight = 20

